### PR TITLE
Add cython as run dependency

### PR DESCRIPTION
**Pull request by PertuyF**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by PertuyF** [comment]
@conda-forge-admin, please rerender

**Comment by PertuyF** [comment]
@conda-forge/hdmedians Could you review this PR please?
This PR corrects a missing `cython` dependency at runtime.

**Comment by ElDeveloper** [comment]
This looks good, although installing hdmedians in a fresh environment as is, does not lead to any failures, package seems to work fine. Were you seeing any problems in particular?

**Comment by PertuyF** [comment]
Yes, I'm building a package that raises an error claiming Cython is required by hdmedians.
And `pip` installs Cython as dependency for `hdmedians` as result of Cython being declared in setup.py's `install_requires` (see [here](https://github.com/daleroberts/hdmedians/blob/master/setup.py)).
To me this strongly suggest that this dependency should be required here.

**Comment by ElDeveloper** [comment]
Thanks for the explanation.

**Comment by PertuyF** [comment]
Looks like I messed up by changing build number to 1 instead of 100x. The conda solver always pulls the former build (1000), so this PR will not have any effect until next version bump.

@ElDeveloper Do you know how we are suppose to quit the 100x build number scheme? It is not relevant anymore now that the new compilers migration is done.

**Comment by ElDeveloper** [comment]
Yeah, I think we would need to make a new release in order to solve this issue with the 100x build. For now, if you submit a PR to change the build number to 1001 that should do. We can keep track of this for the next release and make sure that we use 1.

**Pull request merged**
